spellchecker: aspell

matrix:
- name: markdown
  sources:
  - README.md
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
      - .dictionary.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url: