name: Rust

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build library
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        profile: [dev, release]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.profile }}

      - name: Build
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --profile ${{ matrix.profile }}

  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        uses: auguwu/clippy-action@1.3.0
        with:
          all-features: true
          deny: warnings
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Cargo nextest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest

      - name: Run tests
        uses: clechasseur/rs-cargo@v2
        with:
          command: nextest
          args: run
